Fix multiturn conversation error Groq
MadcowD/ell pull request #312
Opened 2024-10-15 05:51 UTC by reecelikesramen

Fixes #289 
* Groq assistant turns can only have `content: <str>`, no arrays or multimodal
* Warning that Groq cannot handle response_format argument: This is because the way that its passed, I'm working on a separate commit for that.

2024-10-15 05:51 UTC, reecelikesramen commented
I'm working on getting Groq to handle response formatting I got it working in some tests, don't merge yet

2024-10-15 06:11 UTC, reecelikesramen commented
https://console.groq.com/docs/text-chat

2024-10-20 12:52 UTC, MadcowD commented
I'm not sure we should add response format to this because it opinionates the library with a specific prompt

2024-10-20 17:06 UTC, reecelikesramen commented
I agree. I‘ve also been working on patching it with Instructor if that’s preferable.

On Sun, Oct 20, 2024, at 08:52, William Guss wrote:
> I'm not sure we should add response format to this because it opinionates the library with a specific prompt —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this bec
> *DuckDuckGo* removed one tracker. More <https://duckduckgo.com/-if6B_sAfHNraFo0CMIcrW83c1-qRmgrchFeLTlLZ5v_xXoqjbAbwPBJTLITdtztT8xgAwNCYID6j1yPZTBCzpCvQ1AQhC4v-UCzcfJ3cv6RPi6Vj5VX-7vzm-W6kvYI3KGzI0-yUdDLn1nJzzF8_30S0fk1mVih5SEAPQyKDtFyHTuH3jzfFMy92iYAxP3wIdte0mEPoYltTnWhqktZcmNZR-F-Ep7Ihy9_AFNyAjT3HCxER0LMx6HUiE9aADtyGXo2dqffvRAmZOWEX3TbFEk_gatHyqmZtBQp67WNE08C9FW7RJG6f8AF1Qe1p1pRXZh8gFiAwtfjt533uAlk6MZ2HfSyS2f-4pnv_sBSpkW3Wn19vPRCR2PzSoilyY0zYIZRHWLqZofBGtVamrEwDvUlEIdqkDAtl5EBqZ_f7I8H5fKX-V7EixTDXK3bLiJHUPYpDYK>
> Report Spam <https://duckduckgo.com/-if6B_sAfHNraFo0CMIcrW83c1-qRmgrchFeLTlLZ5v_xXoqjbAbwPBJTLITdtztT8xgAwNCYID6j1yPZTBCzpCvQ1AQhC4v-UCzcfJ3cv6RPi6Vj5VX-7vzm-W6kvYI3KGzI0-yUdDLn1nJzzF8_30S0fk1mVih5SEAPQyKDtFyHTuH3jzfFMy92iYAxP3wIdte0mEPoYltTnWhqktZcmNZR-F-Ep7Ihy9_AFNyAjT3HCxER0LMx6HUiE9aADtyGXo2dqffvRAmZOWEX3TbFEk_gatHyqmZtBQp67WNE08C9FW7RJG6f8AF1Qe1p1pRXZh8gFiAwtfjt533uAlk6MZ2HfSyS2f-4pnv_sBSpkW3Wn19vPRCR2PzSoilyY0zYIZRHWLqZofBGtVamrEwDvUlEIdqkDAtl5EBqZ_f7I8H5fKX-V7EixTDXK3bLiJHUPYpDYK>
> 
> 
> I'm not sure we should add response format to this because it opinionates the library with a specific prompt
> 
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/MadcowD/ell/pull/312#issuecomment-2424945813>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAYA6EZYBTD4U7LMHPTTJ6LZ4ORSVAVCNFSM6AAAAABP6KLR3KVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMRUHE2DKOBRGM>.
> You are receiving this because you authored the thread.Message ID: ***@***.***>
>

2024-10-28 04:35 UTC, reecelikesramen commented
@MadcowD Is there any good reason not to leverage Instructor for that? It is widely used and better to not reinvent the wheel if it works well. Also, if I understand correctly, adjusting the system prompt is one of the techniques Instructor uses to coerce tool use and structured responses.

2024-10-29 01:29 UTC, MadcowD commented
@reecelikesramen  i prefer folks ot use instructor and override the client etc (see `instructor_ex`) file for now. I'd like to merge this but I need you to remvoet he "resposne_format" stuff would you mind doing that so we don't add a system prompt to the library?

2024-10-29 01:30 UTC, MadcowD requested changes
see my comment

2024-10-29 01:34 UTC, reecelikesramen commented
@MadcowD here, I reverted to the first commit of this PR which handles just the stated issue

2024-10-29 01:35 UTC, merged

2024-10-29 01:35 UTC, MadcowD commented
Wooo thank you