Separate storage, studio dependencies
MadcowD/ell pull request #343
Opened 2024-10-29 00:56 UTC by alex-dixon

Tried making this as unobtrusive as possible :)

Studio and storage are separated and are available as optional installs.

## Simple
### ell[all]
- Includes anthropic, groq, storage with sqlite, and studio (no change, same as what we have today -- this is the recommended install in the docs)
 

### ell
- Installs `ell` without studio, no tracing/storage support, and the OpenAI provider

## Complex 
Advanced users can specify extras to control what is installed and what isn't:

### ell[sqlite]
- Adds storage via sqlite
- Does not include studio

### ell[studio, postgres]
- Adds ell studio and tracing using postgres as a backend

Fixes #284

2024-10-29 01:10 UTC, MadcowD commented
Would you make a PR to update the docs for this? It's great :)

2024-10-29 01:13 UTC, MadcowD commented on pyproject.toml
> +sqlite = [ 'sqlmodel' ] # do we need a 'sqlite' dependency...?
I think no?

2024-10-29 01:13 UTC, MadcowD commented on pyproject.toml
> +    # allow running stduio by default
Shouldn't studio be included in all?

2024-10-29 01:17 UTC, MadcowD commented
I cannot think of a world where you would want sqlite but not studio? I think something like:
```
pip install ell-ai[all]
pip install ell-ai[studio]
pip install ell-ai[studio, postgres]
```

Would be idea.

2024-10-29 01:20 UTC, MadcowD requested changes
seee other comment

2024-10-30 15:10 UTC, alex-dixon commented
@MadcowD 

> I cannot think of a world where you would want sqlite but not studio?


in pythonland it could be “my program uses a fast api version that doesn’t work with ell studio (but i still want to write traces and have versioning)”. The same goes for any dependency that is required to run studio but not write traces.

I still need to update the error messages but docs are ready. 

Any thoughts on linking to docs in the error message in addition to including an install command?

2024-11-02 18:49 UTC, alex-dixon commented on pyproject.toml
> +postgres = ['sqlmodel', 'psychopg2']
```suggestion
postgres = ['sqlmodel', 'psycopg2']
```

2024-11-11 00:50 UTC, merged